export const TIPOS_VERTICALES:  { key: string; value: string | number }[] =  [
    { key: 'INDUSTRIA', value: 'INDUSTRIA' },
    { key: 'CONSTRUCCION', value: 'CONSTRUCCION' },
    { key: 'COMERCIO', value: 'COMERCIO' },
    { key: 'HOTELES', value: 'HOTELES' },
    { key: 'GRANDES SUPERFICIES', value: 'GRANDES SUPERFICIES' },
    { key: 'SALUD', value: 'SALUD' },
    { key: 'EDUCACION', value: 'EDUCACION' },
    { key: 'GOBIERNO', value: 'GOBIERNO' },
    { key: 'INTEGRADORES', value: 'INTEGRADORES' },
    { key: 'CONTRATISTAS', value: 'CONTRATISTAS' },
    { key: 'TELECOMUNICACIONES', value: 'TELECOMUNICACIONES' },
    { key: 'PETROLEOS', value: 'PETROLEOS' },
    { key: 'ZONAS FRANCAS', value: 'ZONAS FRANCAS' },
    { key: 'DATACENTERS', value: 'DATACENTERS' },
    { key: 'CALLCENTERS', value: 'CALLCENTERS' },
    { key: 'INSTITUCIONAL', value: 'INSTITUCIONAL' },
];